### PR TITLE
Fix: Logging instances of question bank misuse

### LINKED ISSUE #173: Question banks should warn when being used incorrectly
### Subject of the issue/enhancement/features
Currently questions will be reused inside a bank if the desired count is greater than that available. A console message should warn about this error.

### Your environment
* FW v5.22.2
* All browsers
* All devices

### Steps to reproduce
Create a course with an assessment that uses question banks
Set a bank to display 3 but only have 2 blocks/components

### Expected behaviour
2 questions should be printed
Console warning to help debug

### Actual behaviour
2 questions and a repeat are printed
No explanation of why

### PR DESCRIPTION
**Pull request by cahirodoherty-learningpool**
Fixes #173 

[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
### Fix
* Logging in place for when question banks are attempting to print more than available

[//]: # (List appropriate steps for testing if needed)
### Testing
1. Create a course with an assessment that uses question banks
2. Set a bank to display three but only have two blocks/components
3. Two questions should be printed
4. Console warning should be seen

### CODE REVIEW

**Comment by oliverfoster** [comment]
Should probably do one here for when a bank id is used in the blocks that is larger than bankSplits length? 

https://github.com/adaptlearning/adapt-contrib-assessment/blob/4cc415dadf9221b1d7225ac432c805369c182aad/js/adapt-assessmentArticleModel.js#L200-L202

**Comment by cahirodoherty-learningpool** [comment]
> Should probably do one here for when a bank id is used in the blocks that is larger than bankSplits length?
> 
> https://github.com/adaptlearning/adapt-contrib-assessment/blob/4cc415dadf9221b1d7225ac432c805369c182aad/js/adapt-assessmentArticleModel.js#L200-L202

I'm confused. This function is at the article level, but the Bank ID is per-block.

**Comment by oliverfoster** [comment]
Yea, you'll have to get the blocks and check their `_quizBankId`. A QuestionBank instance is made for each questionBank id (which is the bankSplit index+1) and the QuestionBank instance becomes a set of blocks relating to that id. If someone configures a bankSplit of `[2,2,2]` and then assigns a `_quizBankId` of `4`, the code won't warn, it should warn that the assigned id isn't valid.

File: js/adapt-assessmentArticleModel.js [hunk 1]
```diff
@@ -198,6 +198,18 @@ const AssessmentModel = {
   _setupBanks() {
     const assessmentConfig = this.getConfig();
     const bankSplits = assessmentConfig._banks._split.split(',');
+
+    this.findDescendantModels('block')
```
Comment (oliverfoster) [inline js/adapt-assessmentArticleModel.js:202]: `_isAvailable` check?

File: js/adapt-assessmentArticleModel.js [hunk 2]
```diff
@@ -198,6 +198,18 @@ const AssessmentModel = {
...
+      .filter(block => block.findDescendantModels('question').length > 0)).forEach(block => {
+        if (isNaN(block._quizBankId) || block._quizBankId < 1) {
```
Comment (oliverfoster) [inline js/adapt-assessmentArticleModel.js:204]: Could you do variables for these expressions?
```js
const isInvalidNumber = (isNaN(block._quizBankId) || block._quizBankId < 1);
const isOutOfBounds = (block._quizBankId > bankSplits.length);
if (isInvalidNumber) logging.warn(`Bank ID ${block._quizBankId} is not a valid number`);
if (isOutOfBounds) logging.warn(`Bank ID ${block._quizBankId} exceeds the number of available splits (${bankSplits.length})`);
```

It just makes it much easier to read.

**Review by oliverfoster — APPROVED** [review]

**Review by oliverfoster — APPROVED** [review]

File: js/adapt-assessmentArticleModel.js [hunk 3]
```diff
@@ -198,6 +198,16 @@ const AssessmentModel = {
   _setupBanks() {
     const assessmentConfig = this.getConfig();
     const bankSplits = assessmentConfig._banks._split.split(',');
+
+    this.findDescendantModels('block')
+      .filter(block => block.get('_isAvailable'))
+      .filter(block => block.findDescendantModels('question').length > 0)).forEach(block => {
```
Comment (joe-allen-89) [inline js/adapt-assessmentArticleModel.js:204]: Currently getting an error while compiling with line 204 expecting a semi colon. 

Could we not combine the two .filters and have 
.filter(block => (block.get('_isAvailable') && block.findDescendantModels('question').length > 0))

**Review by joe-allen-89 — CHANGES_REQUESTED** [review]

**Review by ethan-lp — APPROVED** [review]

File: js/adapt-assessmentArticleModel.js (hunk 3 above)
Comment (cahirodoherty-learningpool) [reply js/adapt-assessmentArticleModel.js]: Thanks Joe, I missed that

**Review by eleanor-heath — APPROVED** [review]

File: js/adapt-assessmentArticleModel.js (hunk 3 above)
Comment (joe-allen-89) [reply js/adapt-assessmentArticleModel.js]: Apologies, I put an extra closing parentheses which has been copied across. Line 204.

**Comment by oliverfoster** [comment]
Do this now have your approval? @joe-allen-89

File: js/adapt-assessmentArticleModel.js (hunk 2 above)
Comment (joe-allen-89) [reply js/adapt-assessmentArticleModel.js]: block._quizBankId returns as undefined. Think we need const blockAssessmentConfig = block.get('_assessment'); before isInvalidNumber, then replace 'block._quickBankId' with 'blockAssessmentConfig._quizBankID'

File: js/adapt-assessmentQuestionBank.js [hunk 4]
```diff
@@ -26,8 +27,13 @@ class QuestionBank {
...
 
   getRandomQuestionBlocks() {
+    if (this._count > this.unusedQuestionBlocks.length) {
+      logging.warn(`Bank ID ${this._bankId}: Attempting to display ${this._count} question(s), but only ${this.unusedQuestionBlocks.length} available`);
+    }
+
     const questionBlocks = [];
     let i = 0;
+
     while (i++ < this._count) {
```
Comment (joe-allen-89) [inline js/adapt-assessmentQuestionBank.js:37]: At the moment if this._count is higher than the number of questions I'm getting the warning but still getting a duplicate question. Thinking something along the lines of below will stop that behavior. 

```
let count = this._count;
if (this._count > this.unusedQuestionBlocks.length) {
  count = this.unusedQuestionBlocks.length;
  logging.warn(`Bank ID ${this._bankId}: Attempting to display ${this._count} question(s), but only ${this.unusedQuestionBlocks.length} available`);
}

const questionBlocks = [];
let i = 0;

while (i++ < count) {
  const nextBlock = this.unusedQuestionBlocks.shift();
  questionBlocks.push(nextBlock);
}
return questionBlocks;
```

Comment (cahirodoherty-learningpool) [reply js/adapt-assessmentQuestionBank.js:37]: Excellent! Thanks

File: js/adapt-assessmentArticleModel.js (hunk 3 above)
Comment (cahirodoherty-learningpool) [reply js/adapt-assessmentArticleModel.js]: Ah, I should have been more careful! Thanks for the heads up
