### PR TITLE
Fix: Defensive sanity check of assessment data (fixes #178)

### LINKED ISSUE #178: Assessment Data Sanity Check
### Subject of the issue/enhancement/features
Prefacing this by saying this issue was **not** spotted in the core assessment plug-in. This issue presented itself after adding complexity to the base assessment with distributed assessments, assessment banks, SCORM & xAPI etc. It was a rare occurrence, but still locked learners out of the course. @chris-steele added this logic but I believe it could be beneficial to the base plug-in as we expand upon various new types of assessments in the future. 

The proposal is to add a simple sanity check for bad data and correct it if present.

### Your environment
* FW v5.19.6
* Assessment v5.0.2
* All OSs; All Browsers

### Steps to reproduce
You wouldn't be able to reproduce in the core assessment. For example, our Adapt course had learners with low broadband connection as well as a distributed assessment & various banks of assessments. SCORM & xAPI was also added to this project so that contributed to slightly longer load times.

1. Ensure your course is currently SCORM-enabled on an LMS.
2. Before having another attempt at an assessment, throttle your network speeds with browser devtools
3. Upon selecting 'Retry Assessment', close the course while the loading screen is present
4. Even under these circumstances, it may take several times to reproduce.

### Expected behaviour
Upon retry, if a learner's connection to the LMS, the assessment should still:
- reload with suspend data relative to the SCORM data currently committed to the LMS

### Actual behaviour
Upon retry, if a learner's connection to the LMS severed at the most opportune moment, the assessment would:
- reload again with every question still submitted.
- have an assessment model status of still being 'in progress'.
- present no opportunity to retry again. The assessment results would inform you only to complete the above assessment (see screenshot)

### Screenshots (if you can)
image

### PR DESCRIPTION
**Pull request by joe-replin**
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Link the PR to the original issue)

[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
### Fix
* Checks for a conflict in data to see if assessment questions are in a submitted state while the assessment is still 'In Progress'. Fixes #178 

[//]: # (List appropriate steps for testing if needed)
### Testing
You wouldn't be able to reproduce in the core assessment. For example, our Adapt course had learners with low broadband connection as well as a distributed assessment & various banks of assessments. SCORM & xAPI was also added to this project so that contributed to slightly longer load times.
1. Ensure your course is currently SCORM-enabled on an LMS.
2. Before having another attempt at an assessment, throttle your network speeds with browser devtools
3. Upon selecting 'Retry Assessment', close the course while the loading screen is present
4. Even under these circumstances, it may take several times to reproduce.

### CODE REVIEW

**Review by chris-steele — APPROVED** [review]
Looks good, I'm sure there are other items of data that can benefit from this approach both in this plugin and others if anyone has ideas.

**Comment by chris-steele** [comment]
I wonder if when these sorts of contradictions are detected we at least log the occurrence in the console so that there is some record of it for debugging purposes.

File: js/adapt-assessmentArticleModel.js [hunk 1]
```diff
@@ -120,6 +120,12 @@ const AssessmentModel = {
   _onDataReady() {
     // register assessment
     Adapt.assessment.register(this);
+    
+    // sanity check the data
+    const questions = this._getCurrentQuestionComponents();
+    if (this.get('_attemptInProgress') && questions.every(q => q.get('_isSubmitted'))) {
+      this.set('_attemptInProgress', false);
```
Comment (oliverfoster) [inline js/adapt-assessmentArticleModel.js:127]: Add something like:
```js
logging.warn(`Assessment ${this.get('_id') _attemptInProgress corrected as all questions are submitted`);
```

The other situation where this isn't the case is if `this.get('_requireCompletionOf') === -1` as another extension will be adding questions.

File: js/adapt-assessmentArticleModel.js [hunk 2]
```diff
@@ -120,6 +120,13 @@ const AssessmentModel = {
   _onDataReady() {
     // register assessment
     Adapt.assessment.register(this);
+    
+    // sanity check the data
+    const questions = this._getCurrentQuestionComponents();
+    if (this.get('_attemptInProgress') && questions.every(q => q.get('_isSubmitted'))) {
```
Comment (oliverfoster) [inline js/adapt-assessmentArticleModel.js:126]:
```suggestion
    if (this.get('_attemptInProgress') && questions.every(q => q.get('_isSubmitted')) && this.get('_requireCompletionOf') !== Number.POSITIVE_INFINITY) {
```

**Review by joe-allen-89 — APPROVED** [review]
Working as expected in latest FW,
