### PR TITLE
issue/151 Correct completion calculation

### LINKED ISSUE #151: assessment restoration/completion
### Subject of the issue/enhancement/features
It is possible to return to an assessment which has rendered a results component without any feedback.

This seems to be because the assessment is not setting `_isAssessmentComplete: true` when all questions have been answered but trickle hasn't yet been clicked. Without clicking the trickle button, the block is not set to complete and therefore the assessment doesn't update the saved state.

### Your environment
* Adapt framework: 5.18.6

### Steps to reproduce
 * Assessment must be set to `"_isResetOnRevisit": false`. Trickle needs to configured with the button enabled.
 * Complete all questions. Exit before clicking the trickle button on final question.
 * Relaunch and access the assessment. You can scroll down to the results, but no feedback is rendered as the relevant events have not been triggered.

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #151 

### Fixed
* Completion checking was not firing for both blocks and questions

### CODE REVIEW

File: js/adapt-assessmentArticleModel.js [hunk 1]
```diff
@@ -275,7 +275,12 @@ const AssessmentModel = {
   },
 
   _removeQuestionListeners() {
-    this.stopListening(this.getChildren(), 'change:_isInteractionComplete', this._onBlockCompleted);
+    this.listenTo(this, 'bubble:change:_isInteractionComplete', this._onCompletionEvent);
```
Comment (cahirodoherty-learningpool) [inline js/adapt-assessmentArticleModel.js:278]: I think this should be `stopListening`

**Review by eleanor-heath — APPROVED** [review]

**Review by joe-allen-89 — APPROVED** [review]
Tested using FW v5.19.2 and locally and on a test site, without clicking the last trickle on relaunch the assessment results are visible as expected.
